### ISSUE TITLE
[Feature]: Ordering of results should not be biased towards mappings

### ISSUE THREAD

**Issue by olimorris** [mrjones2014/legendary.nvim#218]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

Sharing the following example (where I have typed `comm` and wanted to find `:Comment`):

<img width="984" alt="Screen Shot 2022-11-16 at 13 19 57@2x" src="https://user-images.githubusercontent.com/9512444/202191443-6895e0d4-f64a-41c4-8c1d-5da9cf3d6beb.png">

Mappings take priority over Commands, even though I would argue the 4th result may actually be the best result. For my current usage (everything is a command now) I actually search for the command itself rather than the command description.

Interested to get your thoughts on this.

**Comment by mrjones2014** [comment]
So, the issue isn't necessarily that it's biased towards mapping, it's that when using `vim.ui.select()` we don't have much/any control over the sort order, other than the initial sort order (before you've typed any query).

Technically those first 3 items would have the same matching score, since you typed `comm` and they all contain `comm`, though in different locations.

The only way to fix this would be with user config, providing a custom sorter, e.g. if you're using `dressing.nvim`, providing a custom sorter to `dressing.nvim`.

See: #64 

I'm not sure how exactly the sorter would be implemented, I haven't looked at that issue in a while, but I can try to take another look soon.

The solution will essentially be for `legendary.nvim` to provide some sort of generic sorting function which can then be used in user config to provide custom sorters to your chosen `vim.ui.select()` implementer (e.g. `dressing.nvim`).

**Comment by mrjones2014** [comment]
See also: https://github.com/stevearc/dressing.nvim/issues/22

**Comment by mrjones2014** [comment]
Maybe it would be worth just creating a first-class Telescope picker, since I'm guessing that's what the vast majority of users use. That way we'd have more fine-grained control over how it works with Telescope.

**Comment by mrjones2014** [comment]
Copying some context from #64, the original idea there was also to make it so that user-defined items appear before built-in items.
