### ISSUE TITLE
[Bug]: (Solution found) Failed to open database at /home/username/.local/share/nvim/legendary/legendary_frecency.sqlite3

### ISSUE THREAD

**Issue by kohane27** [mrjones2014/legendary.nvim#363]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Steps to Reproduce

1. Open a file in nvim
2. :Legendary
3. Error output as below

```
[legendary.nvim]
Failed to open database at /home/username/.local/share/nvim/legendary/legendary_frecency.sqlite3: ...in/.local/share/nvim/lazy/sqlite.lua/lua/sqlite/defs.lua:56: /u
sr/bin/sqlite3: cannot dynamically load position-independent executable
Error executing Lua callback: ...vim/lazy/legendary.nvim/lua/legendary/api/db/wrapper.lua:101: attempt to index field 'db' (a nil value)
stack traceback:
        ...vim/lazy/legendary.nvim/lua/legendary/api/db/wrapper.lua:101: in function 'transaction'
        ...nvim/lazy/legendary.nvim/lua/legendary/api/db/client.lua:62: in function 'get_item_scores'
        ...nvim/lazy/legendary.nvim/lua/legendary/data/itemlist.lua:123: in function 'sort_inplace'
        ...share/nvim/lazy/legendary.nvim/lua/legendary/ui/init.lua:55: in function 'select_inner'
        ...share/nvim/lazy/legendary.nvim/lua/legendary/ui/init.lua:103: in function 'select'
        ...al/share/nvim/lazy/legendary.nvim/lua/legendary/init.lua:112: in function 'find'
        ...hare/nvim/lazy/legendary.nvim/lua/legendary/api/cmds.lua:38: in function <...hare/nvim/lazy/legendary.nvim/lua/legendary/api/cmds.lua:10>
```

### Expected Behavior

No error output

### Actual Behavior

![2023-05-05-14-14-19](https://user-images.githubusercontent.com/57322459/236391008-8a9798f4-685c-4d9c-8f32-7f45a148b269.png)

### Minimal Configuration to Reproduce

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "mrjones2014/legendary.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "kkharji/sqlite.lua", -- BUG: removing this and legendary works again
      "stevearc/dressing.nvim",
    },
  },
  -- add any other pugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

require("dressing").setup()

require("legendary").setup({
  -- add any options here
})

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme! it makes testing nicer
vim.cmd([[colorscheme tokyonight]])
```

### Output from :LegendaryLog

<details>
<summary><code>:LegendaryLog</code> output (click to expand)</summary>

```

```
</details>

### Additional Details and/or Screenshots

After disabling "kkharji/sqlite.lua" and the frecency sort option, legendary works again.

Thank you so much for this _legendary_ plugin! It makes using rare commands much easier without having to remember to cmd.

**Comment by mrjones2014** [comment]
I actually ran into this myself as I just switched to Nix package manager, and have already fixed it in the latest release. The issue was that `sqlite.lua` can't find the `sqlite3` library if its not in one of a few specific locations. Can you test again and see if it works with the latest release?

I have this fixed in `legendary.nvim` now but I plan on upstreaming the solution into `sqlite.lua` itself.

**Comment by mrjones2014** [comment]
Upstream PR opened: https://github.com/kkharji/sqlite.lua/pull/169

**Comment by kohane27** [comment]
Hello, thank you for such prompt reply. I really appreciate it.

I've tried the latest git commit version ("42e32d51b685f16fe6b56367b308dbdd9c01dbd0") but I was still greeted with the same error message. Any idea please? Thank you!

**Comment by mrjones2014** [comment]
Still investigating. Root issue is it's failing to load the SQLite shared library.

**Comment by mrjones2014** [comment]
@kohane27 what is your output of:

```
otool -L $(which sqlite3) | grep "sqlite3.dylib"
```

**Comment by mrjones2014** [comment]
Also can you check again if it works now? I've reverted an incorrect fix I made before.

**Comment by kohane27** [comment]
Hello @mrjones2014!

I'm on the commit 27d05b37825370242cf878d858cffe263496fd85 and the error message is gone! Thank you very much for following up on this issue. I really appreciate it.

I'm on Linux and so I don't have `otool` (I believe it's a Mac tool?)

```
➜ which sqlite3
/usr/bin/sqlite3
```

Thanks again!

**Comment by mrjones2014** [comment]
Ah, gotcha. I'm not super familiar with `otool`, just found it in some docs.

Sorry for the inconvenience this caused. For some additional context (cc @olimorris), I originally added that incorrect "fix" as I'm using Nix package manager now, which places `sqlite3` and the corresponding `*.dylib` shared library in a non-standard location (in the Nix store), then symlinks the binary of the correct version into your `$PATH`.

With Nix, the `*.dylib` gets statically included in the `sqlite3` binary which is why it worked for me, but wouldn't work for others.

So the end solution in my case was to simply add an environment variable in my Nix config: `LIBSQLITE="${nixpkgs.sqlite.out}/lib/libsqlite3.dylib"`.

I'll update the README.md suggesting this setup for future Nix users, and resolve this issue with that README.md MR.

Just to make sure I'm fully resolving the issue, @olimorris is the issue resolved on latest master for you as well?

**Comment by olimorris** [comment]
Yep working for me. Thanks so much.
