### ISSUE TITLE
[Enhancement] Recently used maps or commands

### ISSUE THREAD

**Issue by olimorris** [mrjones2014/legendary.nvim#57]
Firstly, thanks for such an amazing plugin. Our correspondence on Reddit last night convinced me to try this out. Totally revolutionising how I use Neovim.

One thing I thought would be a great, low priority enhancement, would be to open `legendary` and see my most commonly used commands at the top of the window.

Appreciate this would be an additional dependency (likely on [sqlite.lua](https://github.com/tami5/sqlite.lua)) so this should be an optional add in for people.

**Comment by mrjones2014** [comment]
Hey, thanks for the GitHub Sponsorship! Really, really appreciate that!

I'm open to a change like this, but it would definitely be optional and opt-in due to needing an extra dependency.

I'm also not entirely sure if it's possible, exactly. I spent a lot of time trying to figure out custom sorting, and it basically looks like that's up to the implementer of `vim.ui.select()` to handle.

I think a feature like this might need to be implemented as a separate plugin, and it would be an integration with your `vim.ui.select()` provider (e.g. you'd need a Telescope plugin to handle it, since I want this plugin to stay agnostic to the `vim.ui.select()` provider).

Alternatively I could make a separate command that shows _only_ your top `n` most commonly used commands, where `n` would be a number configurable via setup.

I'm curious which of these approaches the community would like to see more. With the latter, we could keep that controlled in this plugin and agnostic to `vim.ui.select()`, but not having everything available at once might be a weird UX.

Thoughts?

**Comment by olimorris** [comment]
It's my pleasure. Feels wrong not to sponsor given my whole Neovim workflow will now focus on the plugin ❤️ . (Plus I see you work for a certain company which is another huge love of mine!).

I'll be honest and say I don't like the idea of an external dependency like `sqlite` as it feels bulky. Also, likely to soak up time in support and maintenance instead of core improvements to the plugin.

Your suggestion on a top n list is a great idea though! Much simpler and at least I have a choice in the matter. If I accidentally hit the wrong command a couple of times and it's in my damn list of most recently used then I may be forced to clear the whole list to remove it 😆 .

**Comment by mrjones2014** [comment]
I'm not sure how exactly to do it without something like sqlite. It could be stored in a file in `~/.cache/nvim/` somewhere, but I'm not sure if using a file would be slow, since you'd have to read from it every time you want to find your most common commands, and write to it every time you run a command (also I think we could only track commands run through legendary, I don't think there would be a way for me to track when you type a command manually).

I'd also need to do some research on "frecency" algorithms, as I think that's what we'd want (basically what shows up would be a function of both how recently and how frequently you used each command, it's used for example in Firefox's address bar suggestions, and I think there's a Telescope plugin for frecency sorting as well).

**Comment by olimorris** [comment]
Yeah I actually use that plugin regularly. It's quite clever in that when I boot up Neovim it will sometimes alert me that it's cleared some unused commands.

The more I think about my enhancement, the more I'm now sceptical...because in reality I use my mappings for the most common actions. So if I can't remember the keymap or the command is too verbose, then I reach for `legendary`. And if I can't remember it or I've made the command verbose, it's because it's a low frequency item.

Crikey. Long day.

**Comment by olimorris** [comment]
Really, really great! And per session is a really sensible idea too. Thanks for implementing so quickly!

**Comment by mrjones2014** [comment]
No problem, the idea came to me last night.
