### ISSUE TITLE
Executing a command which requires the word under the cursor

### ISSUE THREAD

**Issue by olimorris** [mrjones2014/legendary.nvim#76]
Hey Mr Jones.

I have 75% converted all of my keymaps, commands and autocmds over to `legendary` now and I couldn't be happier. I've noticed a bit of an edge case regarding some complex mappings I have so thought I'd share as I couldn't find anything in the readme.

I have a nifty keymap which replaces the word under the cursor, across the whole of a buffer:
```lua
vim.api.nvim_set_keymap("n", "<LocalLeader>[", [[:%s/\<<C-r>=expand("<cword>")<CR>\>/]], {})
```

However when I try to incorporate into `legendary`, like so:
```lua
{ "<LocalLeader>[", [[:%s/\<<C-r>=expand("<cword>")<CR>\>/]], description = "Replace cursor words in file"},
```

I get the following error:
```lua
Error executing vim.schedule lua callback: ...k/packer/start/legendary.nvim/lua/legendary/executor.lua:44: Vim(substitute):E486: Pattern not found: \<^A8=expand("<cword>")^K\>
stack traceback:
    [C]: in function 'cmd'
    ...k/packer/start/legendary.nvim/lua/legendary/executor.lua:44: in function 'exec'
    ...k/packer/start/legendary.nvim/lua/legendary/executor.lua:74: in function 'try_execute'
    ...k/packer/start/legendary.nvim/lua/legendary/bindings.lua:264: in function  <...k/packer/start/legendary.nvim/lua/legendary/bindings.lua:263>
```

I'm guessing that as the cursor has focussed to legendary.nvim then executing `cword` yields nothing.

**Comment by mrjones2014** [comment]
Okay this is really neat.

I think the issue is just that we're executing the command before restoring your cursor position, rather than after.

Changing that around will actually make some of my error handling a bit simpler too so that's an added bonus.

I can put together a PR to restore cursor position, _then_ execute, which I think will solve your issue (and now that I think about it, I think that's what should happen anyway).

**Comment by mrjones2014** [comment]
Can you test #77 ?
